# Generated by Django 3.1.3 on 2020-11-04 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_acquainted', models.BooleanField(verbose_name='Ознакомился с правилами')),
                ('taxpayer_and_not_executive', models.BooleanField(verbose_name='Платит налоги в РФ и не является должностным лицом')),
                ('auto_investment_if_its_active', models.BooleanField(verbose_name='Использование автоинвестирования, если оно активировано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_education', models.BooleanField(verbose_name='Высшее экономическое образование')),
                ('value_of_securities_over_6_million', models.BooleanField(verbose_name='Общая стоимость ценных бумаг > 6 млн. Р.')),
                ('experience_in_the_finance_over_2_years', models.BooleanField(verbose_name='Опыт работы в финансовой компании > 2 лет')),
                ('deposits_over_6_million', models.BooleanField(verbose_name='Депозитные металлические счета')),
                ('active_trader', models.BooleanField(verbose_name='Активная торговля ценными бумагами и производными на сумму > 6 млн. Р.')),
                ('already_qualified', models.BooleanField(verbose_name='Уже квалифицирован инвестиционной платформой')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('series_and_number', models.CharField(max_length=10, verbose_name='Серия и номер')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=50, verbose_name='Название')),
                ('date_of_issue', models.DateField(verbose_name='Название')),
                ('department_code', models.CharField(max_length=7, verbose_name='Название')),
                ('issued_by', models.CharField(max_length=70, verbose_name='Название')),
                ('registration_address', models.CharField(max_length=100, verbose_name='Название')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
