# Generated by Django 3.1.3 on 2020-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Паспорт', 'verbose_name_plural': 'Паспорты'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Квалифмкация'},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': 'Правила'},
        ),
        migrations.AlterField(
            model_name='passport',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='department_code',
            field=models.CharField(max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_by',
            field=models.CharField(max_length=70, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='place_of_birth',
            field=models.CharField(max_length=50, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='registration_address',
            field=models.CharField(max_length=100, verbose_name='Адрес регистрации'),
        ),
    ]
