# Generated by Django 3.1.3 on 2020-11-04 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0002_auto_20201105_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='scan_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Разворот с фотографией'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='scan_registration',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Разворот с регистрацией'),
            preserve_default=False,
        ),
    ]
