# Generated by Django 3.1.3 on 2020-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_auto_20201105_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='scan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Разворот с фотографией'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='scan_registration',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Разворот с регистрацией'),
        ),
    ]
